services:
  db:
    container_name: mysql-db
    image: mysql:8

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_managment

    volumes:
      - mysql_data0:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -proot || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 20
  backend:
    container_name: lib-back
    image: medali007/library-backend:latest

    environment:
      MYSQL_ROOT_PASSWORD: root
      DB_PASSWORD: root

    ports:
      - "9080:9080"

    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: lib-front
    image: medali007/library-frontend:latest

    ports:
      - "4202:80"

    depends_on:
      - backend


volumes:
    mysql_data0:
