name: My First CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Version Java avant setup-java
        run: java -version

      - name: Configurer Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compiler le backend
        run: mvn clean compile
        working-directory: ProjectBackend/demo

      - name: Exécuter les tests
        run: mvn test
        working-directory: ProjectBackend/demo

      - name: Package application
        run: mvn clean package
        working-directory: ProjectBackend/demo

      - name: Afficher target
        run: ls -lh target
        working-directory: ProjectBackend/demo

      - name: Build Docker Image
        run: docker build -t library-backend:latest .



  deploy:

    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Voir les fichiers
        run: ls -R


