name: My First CI

on:
  push:

jobs:

  test-job:

    runs-on: ubuntu-latest

    steps:
      - name: Afficher la date
        run: date

      - name: Afficher le dossier courant
        run: pwd

      - name: Afficher les fichiers
        run: ls -la