name: My First CI

on:
  push:

jobs:

  test-job:

    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le dépôt
        uses: actions/checkout@v4

      - name: Afficher le dossier courant
        run: pwd

      - name: Lister les fichiers
        run: ls -la