name: My First CI

on:
  push:

jobs:

  build-backend:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Version Java avant setup-java
        run: java -version

      - name: Configurer Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compiler le backend
        run: mvn clean compile
        working-directory: ProjectBackend/demo

      - name: Exécuter les tests
        run: mvn test
        working-directory: ProjectBackend/demo

      - name: Package application
        run: mvn clean package
        working-directory: ProjectBackend/demo

      - name: Afficher target
        run: ls -lh target
        working-directory: ProjectBackend/demo

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
            -t "${{ secrets.DOCKERHUB_USERNAME }}"/library-backend:latest \
            .
        working-directory: ProjectBackend/demo

      - name: Push Docker Image
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}"/library-backend:latest



  build-frontend:
    needs: build-backend
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ProjectFront/LibraryFront

      - name: Build Angular application
        run: npm run build
        working-directory:  ProjectFront/LibraryFront

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
            -t "${{ secrets.DOCKERHUB_USERNAME }}"/library-frontend:latest \
            .
        working-directory: ProjectFront/LibraryFront

      - name: Push Docker Image
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}"/library-frontend:latest



  deploy:

    needs: build-frontend
    runs-on: self-hosted

    steps:
      - name:  Deploy app
        run: |
          cd ~/deploy-lib-app
          docker compose down
          docker compose pull
          docker compose up -d

      - name: Verify deployment
        run: docker ps


